use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :empex_cookbook, EmpexCookbookWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :empex_cookbook, EmpexCookbook.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "EmpexCookbook",
  hostname: "localhost",
  pool_size: 10,
  loggers: [
    {EmpexCookbook.Metrics, :record_metric, []},
    {EmpexCookbook.EctoInstrument, :trace, []}
  ]

config :statix,
  prefix: "empex_statix",
  host: "127.0.0.1",
  port: 8125

##config :elixometer,
#  reporter: :exometer_report_statsd,
#  update_frequency: 5000,
#  metric_prefix: "empex",
#  env: Mix.env(),
#  # default data are: [:n, :mean, :min, :max, :median, 50, 75, 90, 95, 99, 999]
#  excluded_datapoints: [:n, 50, 75, 999]

##config :exometer_core,
#  report: [
#    reporters: [
#      exometer_report_statsd: [
#        # The hostname needs to use single quotes!
#        hostname: '127.0.0.1',
#        port: 8125,
#        type_map: [{[:_,:_, "histograms", :_, :_], :histogram}]
#      ]
#    ]
#  ]

config :datadog, EmpexCookbook.Tracing,
  service: :empex_metrics,
  adapter: SpandexDatadog.Adapter,
  disabled?: false,
  env: "DEV"
